export const skillsInfo = [
  {
    icon: "fas fa-laptop",
    title: "Client Side",
    skill1: "HTML5",
    skill2: "CSS3",
    skill3: "javascript(Es6)",
    skill4: "React Js",
    skill5: "Rest API",
    skill6: "Bootstrap",
    skill7: "Materil Ui ",
    skill8: "Hosting: Netlify,Firebase",
    className: 'col-sm-6',
  },
  {
    icon: "fas fa-server",
    title: "Server Side",
    skill1: "Node",
    skill2: "Express Js",
    skill3: "MongoDb",
    skill4: "Crud Operation",
    skill5: "Stripe",
    skill6: "Firebase",
    skill7: "Heroku ",
    skill8: "Hosting: Heroqu",
    className: 'col-sm-6',
  },
  {
    icon: "fab fa-accusoft",
    title: "Familiar",
    skill1: "Redux",
    skill2: "React Native",
    skill3: "Next js ",
    skill4: "TypeScript",
    skill5: "wordpress",
    skill6: '',
    skill7: '',
    skill8: '',
    className: 'col-sm-12',
  },
];


